using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Torian.Common.Templating
{

    public static class Utility
    {

        static Utility()
        {
            Regex r = new Regex("[^\\w\\d ]");
            for (int i = 0; i < _badWords.Length; i++)
            {
                _badWords[i] = r.Replace(_badWords[i].ToUpper(), "");
            }
            Array.Sort(_badWords);
        }

        public static bool ContainsBadWordLikeFuckOrShitOrBitchEtc(string theString)
        {
            Regex r = new Regex("[^\\w\\d ]");
            theString = r.Replace(theString.ToUpper(), "");
            foreach (var item in _badWords)
            {
                if (theString.Contains(item))
                {
                    return true;
                }
            }
            return false;
        }

        private static string[] _badWords = {
                                            "ahole",
                                            "anus",
                                            "ash0le",
                                            "ash0les",
                                            "asholes",
                                            "ass",
                                            "Ass Monkey",
                                            "Assface",
                                            "assh0le",
                                            "assh0lez",
                                            "asshole",
                                            "assholes",
                                            "assholz",
                                            "asswipe",
                                            "azzhole",
                                            "bassterds",
                                            "bastard",
                                            "bastards",
                                            "bastardz",
                                            "basterds",
                                            "basterdz",
                                            "Biatch",
                                            "bitch",
                                            "bitches",
                                            "Blow Job",
                                            "boffing",
                                            "butthole",
                                            "buttwipe",
                                            "c0ck",
                                            "c0cks",
                                            "c0k",
                                            "Carpet Muncher",
                                            "cawk",
                                            "cawks",
                                            "Clit",
                                            "cnts",
                                            "cntz",
                                            "cock",
                                            "cockhead",
                                            "cock-head",
                                            "cocks",
                                            "CockSucker",
                                            "cock-sucker",
                                            "crap",
                                            "cum",
                                            "cunt",
                                            "cunts",
                                            "cuntz",
                                            "dick",
                                            "dild0",
                                            "dild0s",
                                            "dildo",
                                            "dildos",
                                            "dilld0",
                                            "dilld0s",
                                            "dominatricks",
                                            "dominatrics",
                                            "dominatrix",
                                            "dyke",
                                            "enema",
                                            "f u c k",
                                            "f u c k e r",
                                            "fag",
                                            "fag1t",
                                            "faget",
                                            "fagg1t",
                                            "faggit",
                                            "faggot",
                                            "fagit",
                                            "fags",
                                            "fagz",
                                            "faig",
                                            "faigs",
                                            "fart",
                                            "flipping the bird",
                                            "fuck",
                                            "fucker",
                                            "fuckin",
                                            "fucking",
                                            "fucks",
                                            "Fudge Packer",
                                            "fuk",
                                            "Fukah",
                                            "Fuken",
                                            "fuker",
                                            "Fukin",
                                            "Fukk",
                                            "Fukkah",
                                            "Fukken",
                                            "Fukker",
                                            "Fukkin",
                                            "g00k",
                                            "gay",
                                            "gayboy",
                                            "gaygirl",
                                            "gays",
                                            "gayz",
                                            "God-damned",
                                            "h00r",
                                            "h0ar",
                                            "h0re",
                                            "hells",
                                            "hoar",
                                            "hoor",
                                            "hoore",
                                            "jackoff",
                                            "jap",
                                            "japs",
                                            "jerk-off",
                                            "jisim",
                                            "jiss",
                                            "jizm",
                                            "jizz",
                                            "knob",
                                            "knobs",
                                            "knobz",
                                            "kunt",
                                            "kunts",
                                            "kuntz",
                                            "Lesbian",
                                            "Lezzian",
                                            "Lipshits",
                                            "Lipshitz",
                                            "masochist",
                                            "masokist",
                                            "massterbait ",
                                            "masstrbait",
                                            "masstrbate",
                                            "masterbaiter",
                                            "masterbate",
                                            "masterbates",
                                            "Motha Fucker",
                                            "Motha Fuker",
                                            "Motha Fukkah",
                                            "Motha Fukker",
                                            "Mother Fucker",
                                            "Mother Fukah",
                                            "Mother Fuker",
                                            "Mother Fukkah",
                                            "Mother Fukker",
                                            "mother-fucker",
                                            "Mutha Fucker",
                                            "Mutha Fukah",
                                            "Mutha Fuker",
                                            "Mutha Fukkah",
                                            "Mutha Fukker",
                                            "n1gr",
                                            "nastt ",
                                            "nigger;",
                                            "nigur;",
                                            "niiger;",
                                            "niigr;",
                                            "orafis",
                                            "orgasim;",
                                            "orgasm",
                                            "orgasum",
                                            "oriface",
                                            "orifice",
                                            "orifiss",
                                            "packi",
                                            "packie",
                                            "packy",
                                            "paki",
                                            "pakie",
                                            "paky",
                                            "pecker",
                                            "peeenus",
                                            "peeenusss",
                                            "peenus",
                                            "peinus",
                                            "pen1s",
                                            "penas",
                                            "penis",
                                            "penis-breath",
                                            "penus",
                                            "penuus",
                                            "Phuc",
                                            "Phuck",
                                            "Phuk",
                                            "Phuker",
                                            "Phukker",
                                            "polac",
                                            "polack",
                                            "polak",
                                            "Poonani",
                                            "pr1c",
                                            "pr1ck",
                                            "pr1k",
                                            "pusse",
                                            "pussee",
                                            "pussy",
                                            "puuke",
                                            "puuker",
                                            "queer",
                                            "queers",
                                            "queerz",
                                            "qweers",
                                            "qweerz",
                                            "qweir",
                                            "recktum",
                                            "rectum",
                                            "retard",
                                            "sadist",
                                            "scank",
                                            "schlong",
                                            "screwing",
                                            "semen",
                                            "sex",
                                            "sexy",
                                            "Sh!t",
                                            "sh1t",
                                            "sh1ter",
                                            "sh1ts",
                                            "sh1tter",
                                            "sh1tz",
                                            "shit",
                                            "shits",
                                            "shitter",
                                            "Shitty",
                                            "Shity",
                                            "shitz",
                                            "Shyt",
                                            "Shyte",
                                            "Shytty",
                                            "Shyty",
                                            "skanck",
                                            "skank",
                                            "skankee",
                                            "skankey",
                                            "skanks",
                                            "Skanky",
                                            "slut",
                                            "sluts",
                                            "Slutty",
                                            "slutz",
                                            "son-of-a-bitch",
                                            "tit",
                                            "turd",
                                            "va1jina",
                                            "vag1na",
                                            "vagiina",
                                            "vagina",
                                            "vaj1na",
                                            "vajina",
                                            "vullva",
                                            "vulva",
                                            "w0p",
                                            "wh00r",
                                            "wh0re",
                                            "whore",
                                            "xrated",
                                            "xxx"
                                            };

    }

}
